applications:
  - name: django-app
    namespace: argocd
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/AnastasiaBndr/goit-devops.git
      targetRevision: main
      path: Project/charts/django-app
      helm:
        parameters:
          - name: image.repository
            value: "{{ .Values.ecrRepoUrl }}"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

ecrRepoUrl: ""